---
- hosts: all
  roles:

  # Applications
  - role: cask_package
    package_name: little-snitch
  - role: cask_package
    package_name: spotify
  - role: cask_package
    package_name: viscosity

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro

  # shell
  - role: oh_my_zsh
  - role: git
    git_user_name: Carl Loa Odin
    git_user_email: carl.loa.odin@klarna.com
  - role: legit
  - role: hub
  - role: brew_package
    package_name: git-extras
  - role: brew_package
    package_name: vim
  - role: brew_package
    tap: homebrew/versions
    package_name: ruby193

  # osx config
  - role: dock
    apps:
    - "/Applications/Airmail Beta.app"
    - "/Applications/Google Chrome.app"
    - /Users/carl.odin/Applications/Spotify.app
    - /Applications/iTerm.app
    folders:
    - path: ~/
    - path: ~/Downloads
    - path: ~/src
      sort: datemodified
  - role: dashboard
    disabled: YES


